"""Native distillation algorithms, organized by their state contract."""

from __future__ import annotations

from importlib import import_module

_ANYFLOW_EXPORTS = {
    "NativeAnyFlowBidirectionalAdapter": ".anyflow.adapters",
    "NativeAnyFlowFARAdapter": ".anyflow.adapters",
    "NativeAnyFlowScoreAdapter": ".anyflow.adapters",
    "NativeAnyFlowBidirectionalOnPolicyLossAdapter": ".anyflow.bidirectional_on_policy",
    "NativeAnyFlowBidirectionalPretrainLossAdapter": ".anyflow.bidirectional_pretrain",
    "NativeAnyFlowOnPolicyTrainingStack": ".anyflow.builder",
    "NativeAnyFlowPretrainingStack": ".anyflow.builder",
    "build_native_anyflow_on_policy_training_stack": ".anyflow.builder",
    "build_native_anyflow_pretraining_stack": ".anyflow.builder",
    "AnyFlowBidirectionalOnPolicyConfig": ".anyflow.config",
    "AnyFlowBidirectionalPretrainConfig": ".anyflow.config",
    "AnyFlowFARConfig": ".anyflow.config",
    "AnyFlowMapConfig": ".anyflow.config",
    "AnyFlowOnPolicyConfig": ".anyflow.config",
    "AnyFlowPretrainConfig": ".anyflow.config",
    "AnyFlowTrainingBatch": ".anyflow.contracts",
    "AnyFlowEMA": ".anyflow.ema",
    "NativeAnyFlowOnPolicyEngine": ".anyflow.engine",
    "NativeAnyFlowPretrainEngine": ".anyflow.engine",
    "NativeAnyFlowOnPolicyLossAdapter": ".anyflow.on_policy",
    "NativeAnyFlowPretrainLossAdapter": ".anyflow.pretrain",
    "AnyFlowRolloutChoice": ".anyflow.rollout",
    "anyflow_bidirectional_rollout": ".anyflow.rollout",
    "anyflow_rollout": ".anyflow.rollout",
    "NativeAnyFlowOnPolicyTrainingSession": ".anyflow.session",
    "NativeAnyFlowPretrainingSession": ".anyflow.session",
    "AnyFlowDecisionRNG": ".anyflow.synchronization",
    "ProcessGroupAnyFlowTensorSynchronizer": ".anyflow.synchronization",
}

_ADAPTIVE_VIDEO_EXPORTS = {
    "ADAPTIVE_VIDEO_DATA_LOADER_STATE_SCHEMA": ".adaptive_video.batching",
    "NativeAdaptiveVideoDataLoader": ".adaptive_video.batching",
    "adaptive_video_real_batch_from_prepared": ".adaptive_video.batching",
    "NativeAdaptiveVideoTrainingStack": ".adaptive_video.builder",
    "build_native_adaptive_video_training_stack": ".adaptive_video.builder",
    "AdaptiveVideoConfig": ".adaptive_video.config",
    "AdaptiveVideoLossAdapter": ".adaptive_video.contracts",
    "AdaptiveVideoRealBatch": ".adaptive_video.contracts",
    "AdaptiveVideoTrainingBatch": ".adaptive_video.contracts",
    "ADAPTIVE_VIDEO_ENGINE_STATE_SCHEMA": ".adaptive_video.engine",
    "NativeAdaptiveVideoTrainEngine": ".adaptive_video.engine",
    "AdaptiveRegressionObservation": ".adaptive_video.math",
    "AdaptiveRegressionWeightResult": ".adaptive_video.math",
    "TemporalRegularizationResult": ".adaptive_video.math",
    "adaptive_regression_weights": ".adaptive_video.math",
    "temporal_variance_regularization": ".adaptive_video.math",
    "AdaptiveVideoLossResult": ".adaptive_video.objective",
    "FlowAdaptiveVideoLossAdapter": ".adaptive_video.objective",
    "AdaptiveRegressionEMA": ".adaptive_video.state",
    "NativeAdaptiveVideoTrainingSession": ".adaptive_video.session",
}

_ADVERSARIAL_DIFFUSION_EXPORTS = {
    "NativeADDTrainingStack": ".adversarial_diffusion.builder",
    "build_native_add_training_stack": ".adversarial_diffusion.builder",
    "ADDConfig": ".adversarial_diffusion.config",
    "ADDTrainingBatch": ".adversarial_diffusion.contracts",
    "ADD_ENGINE_STATE_SCHEMA": ".adversarial_diffusion.engine",
    "ADDTrainResult": ".adversarial_diffusion.engine",
    "NativeADDTrainEngine": ".adversarial_diffusion.engine",
    "NativeADDLossAdapter": ".adversarial_diffusion.objective",
    "ADDRunSummary": ".adversarial_diffusion.session",
    "NativeADDTrainingSession": ".adversarial_diffusion.session",
}

_CAUSAL_CONSISTENCY_EXPORTS = {
    "NativeCausalConsistencyTrainingStack": ".causal_consistency.builder",
    "build_native_causal_consistency_training_stack": ".causal_consistency.builder",
    "CausalConsistencyConfig": ".causal_consistency.config",
    "CausalConsistencySchedule": ".causal_consistency.config",
    "build_causal_consistency_schedule": ".causal_consistency.config",
    "CausalConsistencyTrainingBatch": ".causal_consistency.contracts",
    "FrozenModuleEMA": ".causal_consistency.ema",
    "CAUSAL_CONSISTENCY_ENGINE_STATE_SCHEMA": ".causal_consistency.engine",
    "CausalConsistencyTrainResult": ".causal_consistency.engine",
    "NativeCausalConsistencyTrainEngine": ".causal_consistency.engine",
    "CausalConsistencyLossResult": ".causal_consistency.objective",
    "CausalConsistencyObjective": ".causal_consistency.objective",
    "NativeCausalConsistencyTrainingSession": ".causal_consistency.session",
}

_CAUSAL_ODE_EXPORTS = {
    "NativeCausalODETrainingStack": ".causal_ode.builder",
    "build_native_causal_ode_training_stack": ".causal_ode.builder",
    "CausalODEConfig": ".causal_ode.config",
    "warped_causal_ode_timesteps": ".causal_ode.config",
    "CausalODETrainingBatch": ".causal_ode.contracts",
    "CAUSAL_ODE_ENGINE_STATE_SCHEMA": ".causal_ode.engine",
    "CausalODETrainResult": ".causal_ode.engine",
    "NativeCausalODETrainEngine": ".causal_ode.engine",
    "CausalODELossResult": ".causal_ode.objective",
    "CausalODEObjective": ".causal_ode.objective",
    "PreparedCausalODEBatch": ".causal_ode.objective",
    "NativeCausalODETrainingSession": ".causal_ode.session",
}

_LATENT_CONSISTENCY_EXPORTS = {
    "NativeLatentConsistencyTrainingStack": ".latent_consistency.builder",
    "build_native_latent_consistency_training_stack": ".latent_consistency.builder",
    "LatentConsistencyConfig": ".latent_consistency.config",
    "LatentConsistencyDDIMSchedule": ".latent_consistency.config",
    "LatentConsistencyLossType": ".latent_consistency.config",
    "LatentConsistencyNoiseSchedule": ".latent_consistency.config",
    "LatentConsistencyPredictionType": ".latent_consistency.config",
    "build_latent_consistency_ddim_schedule": ".latent_consistency.config",
    "LatentConsistencyPredictionAdapter": ".latent_consistency.contracts",
    "LatentConsistencyRandomInputs": ".latent_consistency.contracts",
    "LatentConsistencyTrainingBatch": ".latent_consistency.contracts",
    "LATENT_CONSISTENCY_ENGINE_STATE_SCHEMA": ".latent_consistency.engine",
    "LatentConsistencyTrainResult": ".latent_consistency.engine",
    "NativeLatentConsistencyTrainEngine": ".latent_consistency.engine",
    "LatentConsistencyLossResult": ".latent_consistency.objective",
    "LatentConsistencyObjective": ".latent_consistency.objective",
    "NativeLatentConsistencyTrainingSession": ".latent_consistency.session",
}

_PROGRESSIVE_EXPORTS = {
    "NativeProgressiveDistillationTrainingStack": ".progressive.builder",
    "build_native_progressive_distillation_training_stack": ".progressive.builder",
    "ProgressiveDistillationConfig": ".progressive.config",
    "ProgressiveLearningRateAnneal": ".progressive.config",
    "ProgressiveLossWeight": ".progressive.config",
    "ProgressivePredictionType": ".progressive.config",
    "ProgressiveDistillationBatch": ".progressive.contracts",
    "ProgressivePredictionAdapter": ".progressive.contracts",
    "ProgressiveRandomInputs": ".progressive.contracts",
    "NativeProgressiveDistillationTrainEngine": ".progressive.engine",
    "PROGRESSIVE_DISTILLATION_ENGINE_STATE_SCHEMA": ".progressive.engine",
    "ProgressiveDistillationTrainResult": ".progressive.engine",
    "ProgressiveDistillationLossResult": ".progressive.objective",
    "ProgressiveDistillationObjective": ".progressive.objective",
    "NativeProgressiveDistillationTrainingSession": ".progressive.session",
    "ProgressiveDistillationRunSummary": ".progressive.session",
}

_DFD_EXPORTS = {
    "NativeDFDTrainingStack": ".dfd.builder",
    "build_native_dfd_training_stack": ".dfd.builder",
    "DFDConfig": ".dfd.config",
    "DFDDiscriminatorAdapter": ".dfd.contracts",
    "DFDFakeScoreAdapter": ".dfd.contracts",
    "DFDLossAdapter": ".dfd.contracts",
    "DFDPredictionAdapter": ".dfd.contracts",
    "DFDTrainingBatch": ".dfd.contracts",
    "DFD_ENGINE_STATE_SCHEMA": ".dfd.engine",
    "DFDTrainResult": ".dfd.engine",
    "NativeDFDTrainEngine": ".dfd.engine",
    "data_forcing_teacher_data": ".dfd.math",
    "dfd_distribution_gradient": ".dfd.math",
    "dfd_proxy_loss_per_sample": ".dfd.math",
    "shifted_uniform_timesteps": ".dfd.math",
    "DFDLossResult": ".dfd.objective",
    "DFDStudentPrediction": ".dfd.objective",
    "NativeDFDLossAdapter": ".dfd.objective",
    "dfd_teacher_guidance": ".dfd.objective",
    "prepare_dfd_student_prediction": ".dfd.objective",
    "sample_dfd_score_timesteps": ".dfd.objective",
    "sample_dfd_student_timesteps": ".dfd.objective",
    "DFDRunSummary": ".dfd.session",
    "NativeDFDTrainingSession": ".dfd.session",
}

_DIAGONAL_EXPORTS = {
    "NativeDiagonalTrainingStack": ".diagonal.builder",
    "build_native_diagonal_training_stack": ".diagonal.builder",
    "DiagonalObjectiveConfig": ".diagonal.config",
    "DiagonalScheduleConfig": ".diagonal.config",
    "DiagonalCausalAdapter": ".diagonal.contracts",
    "DiagonalFewStepPrediction": ".diagonal.contracts",
    "DiagonalRollout": ".diagonal.contracts",
    "DIAGONAL_ENGINE_STATE_SCHEMA": ".diagonal.engine",
    "NativeDiagonalTrainEngine": ".diagonal.engine",
    "SpatialMotionHead": ".diagonal.motion",
    "register_motion_head": ".diagonal.motion",
    "DiagonalDMDLossAdapter": ".diagonal.objective",
    "DiagonalDMDLossResult": ".diagonal.objective",
    "DiagonalFixedTeacherSampler": ".diagonal.rollout",
    "DiagonalRolloutSampler": ".diagonal.rollout",
    "NativeDiagonalTrainingSession": ".diagonal.session",
}

_DMD_EXPORTS = {
    "NativeDMDTrainingStack": ".dmd.builder",
    "build_native_dmd_training_stack": ".dmd.builder",
    "DMDLossAdapter": ".dmd.contracts",
    "DMDTrainingBatch": ".dmd.contracts",
    "DMD_ENGINE_STATE_SCHEMA": ".dmd.engine",
    "DMDTrainResult": ".dmd.engine",
    "NativeDMDTrainEngine": ".dmd.engine",
    "DMDConfig": ".dmd.objective",
    "DMDLossResult": ".dmd.objective",
    "FewStepPrediction": ".dmd.objective",
    "FewStepSchedule": ".dmd.objective",
    "FlowDMDLossAdapter": ".dmd.objective",
    "dmd_distribution_gradient": ".dmd.objective",
    "dmd_proxy_loss": ".dmd.objective",
    "dmd_teacher_guidance": ".dmd.objective",
    "sample_dmd_score_sigmas": ".dmd.objective",
    "simulate_few_step_student": ".dmd.objective",
    "DMDRunSummary": ".dmd.session",
    "DMDTrainingEngine": ".dmd.session",
    "NativeDMDTrainingSession": ".dmd.session",
}

_DMD2_EXPORTS = {
    "NativeDMD2TrainingStack": ".dmd2.builder",
    "build_native_dmd2_training_stack": ".dmd2.builder",
    "DMD2GuidanceAdapter": ".dmd2.contracts",
    "DMD2LossAdapter": ".dmd2.contracts",
    "DMD2PredictionAdapter": ".dmd2.contracts",
    "DMD2TrainingBatch": ".dmd2.contracts",
    "DMD2_ENGINE_STATE_SCHEMA": ".dmd2.engine",
    "DMD2TrainResult": ".dmd2.engine",
    "NativeDMD2TrainEngine": ".dmd2.engine",
    "dmd2_distribution_gradient": ".dmd2.math",
    "dmd2_generator_adversarial_loss": ".dmd2.math",
    "dmd2_guidance_adversarial_loss": ".dmd2.math",
    "dmd2_proxy_loss_per_sample": ".dmd2.math",
    "dmd2_weighted_total": ".dmd2.math",
    "DMD2Config": ".dmd2.objective",
    "DMD2FewStepPrediction": ".dmd2.objective",
    "DMD2LossResult": ".dmd2.objective",
    "NativeDMD2LossAdapter": ".dmd2.objective",
    "dmd2_teacher_guidance": ".dmd2.objective",
    "sample_dmd2_score_levels": ".dmd2.objective",
    "simulate_dmd2_student": ".dmd2.objective",
    "DMD2RunSummary": ".dmd2.session",
    "NativeDMD2TrainingSession": ".dmd2.session",
}

_RCM_EXPORTS = {
    "NativeRFRCMPredictionAdapter": ".rcm.adapters",
    "NativeRCMTrainingStack": ".rcm.builder",
    "build_native_causal_rcm_training_stack": ".rcm.builder",
    "build_native_rcm_training_stack": ".rcm.builder",
    "causal_rcm_config_from_algorithm": ".rcm.builder",
    "rcm_config_from_algorithm": ".rcm.builder",
    "CausalExactJVPAdapter": ".rcm.causal",
    "CausalRCMConfig": ".rcm.causal",
    "CausalRolloutRequest": ".rcm.causal",
    "CausalSelfForcingAdapter": ".rcm.causal",
    "CausalTeacherForcingAdapter": ".rcm.causal",
    "NativeCausalRCMLossAdapter": ".rcm.causal",
    "RFScoreAdapter": ".rcm.causal",
    "causal_block_pattern": ".rcm.causal",
    "CausalBlockModelAdapter": ".rcm.causal_rollout",
    "NativeCausalSelfForcingRollout": ".rcm.causal_rollout",
    "RCMConfig": ".rcm.config",
    "RCMExactJVPAdapter": ".rcm.contracts",
    "RCMLossAdapter": ".rcm.contracts",
    "RCMLossResult": ".rcm.contracts",
    "RCMPrediction": ".rcm.contracts",
    "RCMPredictionAdapter": ".rcm.contracts",
    "RCMTrainingBatch": ".rcm.contracts",
    "RCM_ENGINE_STATE_SCHEMA": ".rcm.engine",
    "NativeRCMTrainEngine": ".rcm.engine",
    "RCMTrainResult": ".rcm.engine",
    "NativeRCMLossAdapter": ".rcm.objective",
    "NativeRCMTrainingSession": ".rcm.session",
    "RCMRunSummary": ".rcm.session",
    "ProcessGroupRCMTensorSynchronizer": ".rcm.synchronization",
    "RCMTensorSynchronizer": ".rcm.synchronization",
}

_REWARD_FORCING_EXPORTS = {
    "NativeRewardForcingDataLoader": ".reward_forcing.batching",
    "NativeRewardForcingTrainingStack": ".reward_forcing.builder",
    "build_native_reward_forcing_training_stack": ".reward_forcing.builder",
    "RewardForcingConfig": ".reward_forcing.config",
    "RewardForcingTrainingBatch": ".reward_forcing.contracts",
    "NativeRewardForcingTrainEngine": ".reward_forcing.engine",
    "NativeRewardForcingLossAdapter": ".reward_forcing.objective",
    "VideoAlignMotionQualityReward": ".reward_forcing.reward",
    "NativeRewardForcingTrainingSession": ".reward_forcing.session",
    "WanRewardForcingChunkAdapter": ".reward_forcing.wan",
}

_SID_EXPORTS = {
    "NativeSIDTrainingStack": ".sid.builder",
    "build_native_sid_training_stack": ".sid.builder",
    "SIDDiscriminatorAdapter": ".sid.contracts",
    "SIDLossAdapter": ".sid.contracts",
    "SIDPredictionAdapter": ".sid.contracts",
    "SIDTrainingBatch": ".sid.contracts",
    "NativeSIDTrainEngine": ".sid.engine",
    "SID_ENGINE_STATE_SCHEMA": ".sid.engine",
    "SIDTrainResult": ".sid.engine",
    "sid_classifier_free_guidance": ".sid.math",
    "sid_fake_score_adversarial_loss_per_sample": ".sid.math",
    "sid_fake_score_flow_loss_per_sample": ".sid.math",
    "sid_generator_adversarial_loss_per_sample": ".sid.math",
    "sid_generator_loss_per_sample": ".sid.math",
    "sid_score_weight": ".sid.math",
    "NativeSIDLossAdapter": ".sid.objective",
    "SIDConfig": ".sid.objective",
    "SIDFewStepPrediction": ".sid.objective",
    "SIDLossResult": ".sid.objective",
    "sample_sid_score_sigmas": ".sid.objective",
    "simulate_sid_student": ".sid.objective",
    "NativeSIDTrainingSession": ".sid.session",
    "SIDRunSummary": ".sid.session",
}

_SCM_LADD_EXPORTS = {
    "NativeSCMLADDTrainingStack": ".scm_ladd.builder",
    "build_native_scm_ladd_training_stack": ".scm_ladd.builder",
    "SCMLADDDiscriminatorAdapter": ".scm_ladd.contracts",
    "SCMLADDLossAdapter": ".scm_ladd.contracts",
    "SCMLADDLossResult": ".scm_ladd.contracts",
    "SCMLADDTrainingBatch": ".scm_ladd.contracts",
    "SCMVelocityPrediction": ".scm_ladd.contracts",
    "TrigFlowPredictionAdapter": ".scm_ladd.contracts",
    "SCM_LADD_ENGINE_STATE_SCHEMA": ".scm_ladd.engine",
    "NativeSCMLADDTrainEngine": ".scm_ladd.engine",
    "SCMLADDTrainResult": ".scm_ladd.engine",
    "NativeSCMLADDLossAdapter": ".scm_ladd.objective",
    "classifier_free_velocity": ".scm_ladd.math",
    "flow_velocity_to_trigflow": ".scm_ladd.math",
    "ladd_discriminator_hinge_loss": ".scm_ladd.math",
    "ladd_generator_hinge_loss": ".scm_ladd.math",
    "sample_trigflow_timesteps": ".scm_ladd.math",
    "scm_adaptive_loss": ".scm_ladd.math",
    "scm_tangent_target": ".scm_ladd.math",
    "trigflow_clean_prediction": ".scm_ladd.math",
    "trigflow_interpolate": ".scm_ladd.math",
    "trigflow_to_flow_input": ".scm_ladd.math",
    "trigflow_to_flow_time": ".scm_ladd.math",
    "NativeSCMLADDTrainingSession": ".scm_ladd.session",
    "SCMLADDRunSummary": ".scm_ladd.session",
}

_SELF_FORCING_EXPORTS = {
    "NativeSelfForcingDataLoader": ".self_forcing.batching",
    "NativeSelfForcingTrainingStack": ".self_forcing.builder",
    "build_native_self_forcing_training_stack": ".self_forcing.builder",
    "SelfForcingConfig": ".self_forcing.config",
    "shifted_few_step_schedule": ".self_forcing.config",
    "CausalChunkAdapter": ".self_forcing.contracts",
    "SelfForcingRollout": ".self_forcing.contracts",
    "DelayedSelfForcingEMA": ".self_forcing.ema",
    "SelfForcingRolloutSampler": ".self_forcing.rollout",
    "NativeSelfForcingTrainingSession": ".self_forcing.session",
    "WanSelfForcingChunkAdapter": ".self_forcing.wan",
}

_SELF_GRADIENT_FORCING_EXPORTS = {
    "NativeSelfGradientForcingTrainingStack": ".self_gradient_forcing.builder",
    "build_native_self_gradient_forcing_training_stack": ".self_gradient_forcing.builder",
    "CacheTargetMode": ".self_gradient_forcing.config",
    "ExitStepRankMode": ".self_gradient_forcing.config",
    "SelfGradientForcingConfig": ".self_gradient_forcing.config",
    "shifted_flow_timestep": ".self_gradient_forcing.config",
    "SelfGradientForcingAdapter": ".self_gradient_forcing.contracts",
    "SelfGradientForcingReplay": ".self_gradient_forcing.contracts",
    "SELF_GRADIENT_FORCING_ENGINE_STATE_SCHEMA": ".self_gradient_forcing.engine",
    "NativeSelfGradientForcingTrainEngine": ".self_gradient_forcing.engine",
    "SELF_GRADIENT_FORCING_RNG_STATE_SCHEMA": ".self_gradient_forcing.rollout",
    "SelfGradientForcingSampler": ".self_gradient_forcing.rollout",
    "NativeSelfGradientForcingTrainingSession": ".self_gradient_forcing.session",
    "WanSelfGradientForcingAdapter": ".self_gradient_forcing.wan",
}

_SGMD_EXPORTS = {
    "NativeSGMDTrainingStack": ".sgmd.builder",
    "build_native_sgmd_training_stack": ".sgmd.builder",
    "SGMDConfig": ".sgmd.config",
    "shifted_flow_sigma": ".sgmd.config",
    "SGMDLossAdapter": ".sgmd.contracts",
    "SGMDPredictionAdapter": ".sgmd.contracts",
    "SGMDTrainingBatch": ".sgmd.contracts",
    "SGMD_ENGINE_STATE_SCHEMA": ".sgmd.engine",
    "NativeSGMDTrainEngine": ".sgmd.engine",
    "SGMDTrainResult": ".sgmd.engine",
    "NativeSGMDLossAdapter": ".sgmd.objective",
    "SGMDLossResult": ".sgmd.objective",
    "SGMDRollout": ".sgmd.objective",
    "sample_sgmd_score_sigmas": ".sgmd.objective",
    "simulate_sgmd_student": ".sgmd.objective",
    "NativeSGMDTrainingSession": ".sgmd.session",
    "SGMDRunSummary": ".sgmd.session",
}

_SCALE_WISE_EXPORTS = {
    "NativeScaleWiseTrainingStack": ".scale_wise.builder",
    "build_native_scale_wise_training_stack": ".scale_wise.builder",
    "ScaleWiseConfig": ".scale_wise.config",
    "ScaleWiseSchedule": ".scale_wise.config",
    "flow_match_solver_sigmas": ".scale_wise.config",
    "ScaleWiseCriticAdapter": ".scale_wise.contracts",
    "ScaleWiseLossAdapter": ".scale_wise.contracts",
    "ScaleWisePredictionAdapter": ".scale_wise.contracts",
    "ScaleWiseTrainingBatch": ".scale_wise.contracts",
    "NativeScaleWiseTrainEngine": ".scale_wise.engine",
    "SCALE_WISE_ENGINE_STATE_SCHEMA": ".scale_wise.engine",
    "ScaleWiseTrainResult": ".scale_wise.engine",
    "FlowScaleWiseLossAdapter": ".scale_wise.objective",
    "ScaleWiseLossResult": ".scale_wise.objective",
    "NativeScaleWiseTrainingSession": ".scale_wise.session",
    "ScaleWiseRunSummary": ".scale_wise.session",
    "SD3AdapterDisabledTeacherAdapter": ".scale_wise.sd3",
    "SD3ScaleWiseCriticAdapter": ".scale_wise.sd3",
    "SD3ScaleWiseCriticModule": ".scale_wise.sd3",
    "SD3ScaleWisePredictionAdapter": ".scale_wise.sd3",
    "sd3_velocity_and_features": ".scale_wise.sd3",
}

_SENSEFLOW_EXPORTS = {
    "NativeSenseFlowTrainingStack": ".senseflow.builder",
    "build_native_senseflow_training_stack": ".senseflow.builder",
    "SenseFlowConfig": ".senseflow.config",
    "SenseFlowTrainingBatch": ".senseflow.contracts",
    "SENSEFLOW_ENGINE_STATE_SCHEMA": ".senseflow.engine",
    "NativeSenseFlowTrainEngine": ".senseflow.engine",
    "SenseFlowTrainResult": ".senseflow.engine",
    "NativeSenseFlowLossAdapter": ".senseflow.objective",
    "NativeSenseFlowTrainingSession": ".senseflow.session",
    "SenseFlowRunSummary": ".senseflow.session",
}

_EXPORTS = {
    **_ANYFLOW_EXPORTS,
    **_ADAPTIVE_VIDEO_EXPORTS,
    **_ADVERSARIAL_DIFFUSION_EXPORTS,
    **_CAUSAL_CONSISTENCY_EXPORTS,
    **_CAUSAL_ODE_EXPORTS,
    **_LATENT_CONSISTENCY_EXPORTS,
    **_PROGRESSIVE_EXPORTS,
    **_DFD_EXPORTS,
    **_DIAGONAL_EXPORTS,
    **_DMD_EXPORTS,
    **_DMD2_EXPORTS,
    **_RCM_EXPORTS,
    **_REWARD_FORCING_EXPORTS,
    **_SID_EXPORTS,
    **_SCM_LADD_EXPORTS,
    **_SELF_FORCING_EXPORTS,
    **_SELF_GRADIENT_FORCING_EXPORTS,
    **_SGMD_EXPORTS,
    **_SCALE_WISE_EXPORTS,
    **_SENSEFLOW_EXPORTS,
}

__all__ = list(_EXPORTS)


def __getattr__(name: str) -> object:
    module_name = _EXPORTS.get(name)
    if module_name is None:
        raise AttributeError(name)
    value = getattr(import_module(module_name, __name__), name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(__all__))
