"""Reward model recipe contracts."""

from .videoalign import (
    VIDEOALIGN_BASE_MODEL_REPOSITORY,
    VIDEOALIGN_BASE_MODEL_REVISION,
    VIDEOALIGN_CALIBRATION_MEAN,
    VIDEOALIGN_CALIBRATION_STD,
    VIDEOALIGN_CHECKPOINT_FILE,
    VIDEOALIGN_CHECKPOINT_REPOSITORY,
    VIDEOALIGN_CHECKPOINT_REVISION,
    VIDEOALIGN_CHECKPOINT_SHA256,
    VIDEOALIGN_CHECKPOINT_SIZE_BYTES,
    VIDEOALIGN_REWARD_IDS,
    VideoAlignRewardSpec,
)

__all__ = [
    "VIDEOALIGN_BASE_MODEL_REPOSITORY",
    "VIDEOALIGN_BASE_MODEL_REVISION",
    "VIDEOALIGN_CALIBRATION_MEAN",
    "VIDEOALIGN_CALIBRATION_STD",
    "VIDEOALIGN_CHECKPOINT_FILE",
    "VIDEOALIGN_CHECKPOINT_REPOSITORY",
    "VIDEOALIGN_CHECKPOINT_REVISION",
    "VIDEOALIGN_CHECKPOINT_SHA256",
    "VIDEOALIGN_CHECKPOINT_SIZE_BYTES",
    "VIDEOALIGN_REWARD_IDS",
    "VideoAlignRewardSpec",
]
