#!/usr/bin/env bash
# Compile a per-tier lockfile for requirements/worldfoundry-unified.txt (plan I-05).
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
TIER="${1:-}"
UV_BIN="${UV:-uv}"
PYTHON_BIN="${PYTHON:-python3}"

usage() {
  cat <<'EOF'
Usage: bash scripts/setup/compile_unified_lock.sh <cu121|cu124|cu128>

Requires uv on PATH (or set UV=/path/to/uv). Writes:
  requirements/lock/worldfoundry-unified.<tier>.lock.txt

After compile, validates that the resolved torch== pin exists on the CUDA
wheel index so PyPI fall-through cannot produce a misleading lock.
EOF
}

case "${TIER}" in
  cu121|cu124|cu128) ;;
  -h|--help|"")
    usage
    [[ -n "${TIER}" ]] || exit 2
    exit 0
    ;;
  *)
    echo "Unsupported tier: ${TIER}" >&2
    usage >&2
    exit 2
    ;;
esac

if ! command -v "${UV_BIN}" >/dev/null 2>&1; then
  echo "uv is required to compile lockfiles. Install uv or set UV=..." >&2
  exit 1
fi

OUT="${ROOT}/requirements/lock/worldfoundry-unified.${TIER}.lock.txt"
INDEX_URL="${WORLDFOUNDRY_TORCH_INDEX_URL:-https://download.pytorch.org/whl/${TIER}}"
PYPI_URL="${WORLDFOUNDRY_PYPI_INDEX_URL:-https://pypi.org/simple}"

echo "Compiling ${OUT}"
echo "Torch index: ${INDEX_URL}"

tmp="$(mktemp)"
trap 'rm -f "${tmp}"' EXIT

# Header documents the indices used for this compile.
{
  printf '%s\n' \
    "# WorldFoundry unified lock for CUDA tier ${TIER}." \
    "# Generated by scripts/setup/compile_unified_lock.sh" \
    "# --index-url ${INDEX_URL}" \
    "# --extra-index-url ${PYPI_URL}" \
    "#"
  "${UV_BIN}" pip compile \
    --python-version 3.11 \
    --index-url "${INDEX_URL}" \
    --extra-index-url "${PYPI_URL}" \
    --emit-index-url \
    --no-strip-extras \
    "${ROOT}/requirements/worldfoundry-unified.txt"
} >"${tmp}"

"${PYTHON_BIN}" "${ROOT}/scripts/setup/validate_unified_lock_tier.py" \
  "${tmp}" \
  --tier "${TIER}" \
  --index-url "${INDEX_URL}"

mv "${tmp}" "${OUT}"
trap - EXIT
echo "Wrote ${OUT}"
