#!/usr/bin/env bash
# Compile a per-tier lockfile for requirements/worldfoundry-unified.txt (plan I-05).
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
TIER="${1:-}"
MODE="write"
UV_BIN="${UV:-uv}"
PYTHON_BIN="${PYTHON:-python3}"

usage() {
  cat <<'USAGE'
Usage: bash scripts/setup/compile_unified_lock.sh <cu121|cu124|cu128> [--check]

Requires uv on PATH (or set UV=/path/to/uv). Writes:
  requirements/lock/worldfoundry-unified.<tier>.lock.txt

Applies requirements/cuda/<tier>-torch.txt (TIER_TORCH_SPECS / I-03) as
--constraint so uv cannot fall through to a PyPI torch build outside the
CUDA index. After compile, validates the resolved torch== pin against the
CUDA wheel index listing.

With --check: recompile to a temp file and refuse if package pins drift from
the committed lock (placeholders with no pins are skipped).
USAGE
}

if [[ "${2:-}" == "--check" ]]; then
  MODE="check"
elif [[ -n "${2:-}" ]]; then
  echo "Unexpected argument: ${2}" >&2
  usage >&2
  exit 2
fi

case "${TIER}" in
  cu121|cu124|cu128) ;;
  -h|--help|"")
    usage
    [[ -n "${TIER}" ]] || exit 2
    exit 0
    ;;
  *)
    echo "Unsupported tier: ${TIER}" >&2
    usage >&2
    exit 2
    ;;
esac

if ! command -v "${UV_BIN}" >/dev/null 2>&1; then
  echo "uv is required to compile lockfiles. Install uv or set UV=..." >&2
  exit 1
fi

OUT="${ROOT}/requirements/lock/worldfoundry-unified.${TIER}.lock.txt"
CONSTRAINT_REL="requirements/cuda/${TIER}-torch.txt"
REQ_REL="requirements/worldfoundry-unified.txt"
CONSTRAINT="${ROOT}/${CONSTRAINT_REL}"
REQ="${ROOT}/${REQ_REL}"
INDEX_URL="${WORLDFOUNDRY_TORCH_INDEX_URL:-https://download.pytorch.org/whl/${TIER}}"
PYPI_URL="${WORLDFOUNDRY_PYPI_INDEX_URL:-https://pypi.org/simple}"

if [[ ! -f "${CONSTRAINT}" ]]; then
  echo "missing tier torch constraint stub: ${CONSTRAINT_REL}" >&2
  exit 1
fi

if [[ "${MODE}" == "check" ]]; then
  if [[ ! -f "${OUT}" ]]; then
    echo "missing committed lock: ${OUT}" >&2
    exit 1
  fi
  if grep -q 'Do not invent' "${OUT}"; then
    echo "check-unified-lock: ${TIER} lock is still a placeholder; skip"
    exit 0
  fi
fi

echo "Compiling ${OUT} (mode=${MODE})"
echo "Torch index: ${INDEX_URL}"
echo "Constraints: ${CONSTRAINT_REL}"

tmp="$(mktemp)"
trap 'rm -f "${tmp}"' EXIT

{
  printf '%s\n' \
    "# WorldFoundry unified lock for CUDA tier ${TIER}." \
    "# Generated by scripts/setup/compile_unified_lock.sh" \
    "# --index-url ${INDEX_URL}" \
    "# --extra-index-url ${PYPI_URL}" \
    "# --constraint ${CONSTRAINT_REL}" \
    "#"
  # Compile from repo root so uv's autogenerated command comment stays relative.
  (
    cd "${ROOT}"
    "${UV_BIN}" pip compile \
      --python-version 3.11 \
      --index-url "${INDEX_URL}" \
      --extra-index-url "${PYPI_URL}" \
      --constraint "${CONSTRAINT_REL}" \
      --emit-index-url \
      --no-strip-extras \
      "${REQ_REL}"
  )
} >"${tmp}"

"${PYTHON_BIN}" "${ROOT}/scripts/setup/validate_unified_lock_tier.py" \
  "${tmp}" \
  --tier "${TIER}" \
  --index-url "${INDEX_URL}"

if [[ "${MODE}" == "check" ]]; then
  PYTHONPATH="${ROOT}${PYTHONPATH:+:${PYTHONPATH}}" "${PYTHON_BIN}" - "${OUT}" "${tmp}" <<'PY'
import sys
from pathlib import Path

from worldfoundry.runtime.unified_lock_pins import package_pins

committed = Path(sys.argv[1]).read_text(encoding="utf-8")
fresh = Path(sys.argv[2]).read_text(encoding="utf-8")
left = package_pins(committed)
right = package_pins(fresh)
if left != right:
    only_left = sorted(set(left) - set(right))
    only_right = sorted(set(right) - set(left))
    changed = sorted(
        name for name in set(left) & set(right) if left[name] != right[name]
    )
    print("unified lock pin drift detected:", file=sys.stderr)
    if only_left:
        print(f"  only in committed: {', '.join(only_left[:20])}", file=sys.stderr)
    if only_right:
        print(f"  only in recompile: {', '.join(only_right[:20])}", file=sys.stderr)
    for name in changed[:20]:
        print(f"  {name}: {left[name]} -> {right[name]}", file=sys.stderr)
    raise SystemExit(1)
print(f"OK: {sys.argv[1]} pins match recompile ({len(left)} packages)")
PY
  exit 0
fi

mv "${tmp}" "${OUT}"
trap - EXIT
echo "Wrote ${OUT}"
