if(NOT DEFINED INPUT_LIBRARY OR NOT EXISTS "${INPUT_LIBRARY}")
  message(FATAL_ERROR "Native dispatcher library does not exist: ${INPUT_LIBRARY}")
endif()
if(NOT DEFINED OUTPUT_MANIFEST)
  message(FATAL_ERROR "OUTPUT_MANIFEST is required")
endif()

file(SHA256 "${INPUT_LIBRARY}" LIBRARY_SHA256)
get_filename_component(LIBRARY_FILENAME "${INPUT_LIBRARY}" NAME)

if(TORCH_CUDA STREQUAL "")
  set(TORCH_CUDA_JSON "null")
else()
  set(TORCH_CUDA_JSON "\"${TORCH_CUDA}\"")
endif()
if(CXX11_ABI STREQUAL "1")
  set(CXX11_ABI_JSON "true")
else()
  set(CXX11_ABI_JSON "false")
endif()

file(WRITE "${OUTPUT_MANIFEST}" "{\n")
file(APPEND "${OUTPUT_MANIFEST}" "  \"manifest_schema_version\": ${MANIFEST_SCHEMA_VERSION},\n")
file(APPEND "${OUTPUT_MANIFEST}" "  \"operator_abi_version\": ${OPERATOR_ABI_VERSION},\n")
file(APPEND "${OUTPUT_MANIFEST}" "  \"operator_schema_hash\": \"${OPERATOR_SCHEMA_HASH}\",\n")
file(APPEND "${OUTPUT_MANIFEST}" "  \"build_id\": \"${BUILD_ID}\",\n")
file(APPEND "${OUTPUT_MANIFEST}" "  \"package_version\": \"${PACKAGE_VERSION}\",\n")
file(APPEND "${OUTPUT_MANIFEST}" "  \"source_revision\": \"${SOURCE_REVISION}\",\n")
file(APPEND "${OUTPUT_MANIFEST}" "  \"source_tree_hash\": \"${SOURCE_TREE_HASH}\",\n")
file(APPEND "${OUTPUT_MANIFEST}" "  \"torch_version\": \"${TORCH_VERSION}\",\n")
file(APPEND "${OUTPUT_MANIFEST}" "  \"torch_cuda\": ${TORCH_CUDA_JSON},\n")
file(APPEND "${OUTPUT_MANIFEST}" "  \"cxx11_abi\": ${CXX11_ABI_JSON},\n")
file(APPEND "${OUTPUT_MANIFEST}" "  \"links_libtorch_python\": false,\n")
file(APPEND "${OUTPUT_MANIFEST}" "  \"library\": \"lib/${LIBRARY_FILENAME}\",\n")
file(APPEND "${OUTPUT_MANIFEST}" "  \"library_sha256\": \"${LIBRARY_SHA256}\",\n")
file(APPEND "${OUTPUT_MANIFEST}" "  \"compiler\": {\"id\": \"${CXX_COMPILER_ID}\", \"version\": \"${CXX_COMPILER_VERSION}\", \"cxx_standard\": ${CXX_STANDARD}},\n")
file(APPEND "${OUTPUT_MANIFEST}" "  \"libstdcxx\": {\"path\": \"${LIBSTDCXX_PATH}\", \"sha256\": \"${LIBSTDCXX_SHA256}\"},\n")
file(APPEND "${OUTPUT_MANIFEST}" "  \"compile_flags\": [\"-std=c++${CXX_STANDARD}\", \"_GLIBCXX_USE_CXX11_ABI=${CXX11_ABI}\"],\n")
file(APPEND "${OUTPUT_MANIFEST}" "  \"nvcc_version\": null,\n")
file(APPEND "${OUTPUT_MANIFEST}" "  \"sm_targets\": [],\n")
file(APPEND "${OUTPUT_MANIFEST}" "  \"sass_targets\": [],\n")
file(APPEND "${OUTPUT_MANIFEST}" "  \"ptx_targets\": [],\n")
file(APPEND "${OUTPUT_MANIFEST}" "  \"capabilities\": []\n")
file(APPEND "${OUTPUT_MANIFEST}" "}\n")
