"""Algorithm-owned RL objectives and execution stacks."""

from __future__ import annotations

from importlib import import_module

_EXPORTS = {
    "DDRL_ADVANTAGE_EPSILON": ".ddrl.objective",
    "DDRL_ENGINE_STATE_SCHEMA": ".ddrl.engine",
    "DDRLAdvantages": ".ddrl.objective",
    "DDRLDataRegularizerAdapter": ".ddrl.contracts",
    "DDRLIterationResult": ".ddrl.session",
    "DDRLLoss": ".ddrl.objective",
    "DDRLReplayAdapter": ".ddrl.contracts",
    "DDRLRewardAdapter": ".ddrl.contracts",
    "DDRLRolloutAdapter": ".ddrl.contracts",
    "DDRLRolloutBatch": ".ddrl.contracts",
    "DDRLStepResult": ".ddrl.engine",
    "DDRLTrajectory": ".ddrl.contracts",
    "NativeDDRLEngine": ".ddrl.engine",
    "NativeDDRLTrainingStack": ".ddrl.builder",
    "NativeDDRLTrainingSession": ".ddrl.session",
    "build_native_ddrl_training_stack": ".ddrl.builder",
    "ddrl_group_advantages": ".ddrl.objective",
    "ddrl_loss": ".ddrl.objective",
    "BAGEL_FLOW_UNIGRPO_ENGINE_STATE_SCHEMA": ".bagel_flow_unigrpo.engine",
    "BagelFlowUniGRPOIterationResult": ".bagel_flow_unigrpo.session",
    "BagelFlowUniGRPOLoss": ".bagel_flow_unigrpo.objective",
    "BagelFlowUniGRPOStageAlgorithm": ".bagel_flow_unigrpo.algorithm",
    "BagelFlowUniGRPOStepResult": ".bagel_flow_unigrpo.engine",
    "NativeBagelFlowUniGRPOEngine": ".bagel_flow_unigrpo.engine",
    "NativeBagelFlowUniGRPOTrainingSession": ".bagel_flow_unigrpo.session",
    "bagel_flow_unigrpo_loss": ".bagel_flow_unigrpo.objective",
    "build_native_bagel_flow_unigrpo_engine": ".bagel_flow_unigrpo.engine",
    "DANCE_GRPO_ENGINE_STATE_SCHEMA": ".dance_grpo.engine",
    "DanceGRPOIterationResult": ".dance_grpo.session",
    "DanceGRPOStageAlgorithm": ".dance_grpo.algorithm",
    "NativeDanceGRPOEngine": ".dance_grpo.engine",
    "NativeDanceGRPOTrainingSession": ".dance_grpo.session",
    "build_native_dance_grpo_engine": ".dance_grpo.engine",
    "sample_dance_update_step_mask": ".dance_grpo.update_steps",
    "DIFFUSION_DPO_ENGINE_STATE_SCHEMA": ".diffusion_dpo.engine",
    "DiffusionDPOBatch": ".diffusion_dpo.contracts",
    "DiffusionDPOForwardSample": ".diffusion_dpo.objective",
    "DiffusionDPOLoss": ".diffusion_dpo.objective",
    "DiffusionDPORunSummary": ".diffusion_dpo.session",
    "DiffusionDPOStepResult": ".diffusion_dpo.engine",
    "NativeDiffusionDPOEngine": ".diffusion_dpo.engine",
    "NativeDiffusionDPOTrainingStack": ".diffusion_dpo.builder",
    "NativeDiffusionDPOTrainingSession": ".diffusion_dpo.session",
    "build_native_diffusion_dpo_training_stack": ".diffusion_dpo.builder",
    "diffusion_dpo_forward_process": ".diffusion_dpo.objective",
    "diffusion_dpo_loss": ".diffusion_dpo.objective",
    "sample_diffusion_dpo_forward_process": ".diffusion_dpo.objective",
    "DiffusionNFTRewardAdapter": ".diffusion_nft.contracts",
    "DIFFUSION_NFT_ENGINE_STATE_SCHEMA": ".diffusion_nft.engine",
    "DIFFUSION_NFT_OLD_POLICY_SCHEDULES": ".diffusion_nft.contracts",
    "DiffusionNFTForwardSample": ".diffusion_nft.objective",
    "DiffusionNFTLoss": ".diffusion_nft.objective",
    "DiffusionNFTRollout": ".diffusion_nft.contracts",
    "DiffusionNFTTerminalLatents": ".diffusion_nft.contracts",
    "DiffusionNFTRunSummary": ".diffusion_nft.session",
    "DiffusionNFTRewardWeights": ".diffusion_nft.objective",
    "DiffusionNFTStepResult": ".diffusion_nft.engine",
    "NativeDiffusionNFTEngine": ".diffusion_nft.engine",
    "NativeDiffusionNFTTerminalCollector": ".diffusion_nft.collection",
    "NativeDiffusionNFTTrainingStack": ".diffusion_nft.builder",
    "NativeDiffusionNFTTrainingSession": ".diffusion_nft.session",
    "OldPolicyRefresh": ".diffusion_nft.contracts",
    "build_native_diffusion_nft_training_stack": ".diffusion_nft.builder",
    "diffusion_nft_forward_process": ".diffusion_nft.objective",
    "diffusion_nft_loss": ".diffusion_nft.objective",
    "diffusion_nft_reward_weights": ".diffusion_nft.objective",
    "AnchorField": ".stage",
    "ClippedPolicyLoss": ".flow_grpo.objective",
    "FLOW_DPPO_ENGINE_STATE_SCHEMA": ".flow_dppo.engine",
    "FLOW_GRPO_ENGINE_STATE_SCHEMA": ".flow_grpo.engine",
    "FlowDPPOLoss": ".flow_dppo.objective",
    "FlowDPPOIterationResult": ".flow_dppo.session",
    "FlowDPPOStepResult": ".flow_dppo.engine",
    "FlowDPPOStageAlgorithm": ".flow_dppo.algorithm",
    "FlowGRPOIterationResult": ".flow_grpo.session",
    "FlowGRPOStepResult": ".flow_grpo.engine",
    "FlowGRPOStageAlgorithm": ".flow_grpo.algorithm",
    "GRPO_GUARD_ENGINE_STATE_SCHEMA": ".grpo_guard.engine",
    "GRPOGuardIterationResult": ".grpo_guard.session",
    "GRPOGuardLoss": ".grpo_guard.objective",
    "GRPOGuardStageAlgorithm": ".grpo_guard.algorithm",
    "GRPOGuardStepResult": ".grpo_guard.engine",
    "NativeGRPOGuardEngine": ".grpo_guard.engine",
    "NativeGRPOGuardTrainingSession": ".grpo_guard.session",
    "build_native_grpo_guard_engine": ".grpo_guard.engine",
    "grpo_guard_policy_loss": ".grpo_guard.objective",
    "NativeFlowDPPOEngine": ".flow_dppo.engine",
    "NativeFlowDPPOTrainingSession": ".flow_dppo.session",
    "NativeFlowGRPOEngine": ".flow_grpo.engine",
    "NativeFlowGRPOTrainingSession": ".flow_grpo.session",
    "MIX_GRPO_ENGINE_STATE_SCHEMA": ".mix_grpo.engine",
    "MixGRPOIterationResult": ".mix_grpo.session",
    "MixGRPOStageAlgorithm": ".mix_grpo.algorithm",
    "NativeMixGRPOEngine": ".mix_grpo.engine",
    "NativeMixGRPOTrainingSession": ".mix_grpo.session",
    "build_native_mix_grpo_engine": ".mix_grpo.engine",
    "NativeFlowPolicyTrainingStack": ".flow_policy.builder",
    "StageAlgorithm": ".stage",
    "StageAnchor": ".stage",
    "StageLoss": ".stage",
    "build_native_flow_dppo_engine": ".flow_dppo.engine",
    "build_native_flow_grpo_engine": ".flow_grpo.engine",
    "build_native_flow_policy_training_stack": ".flow_policy.builder",
    "clipped_policy_loss": ".flow_grpo.objective",
    "flow_dppo_policy_loss": ".flow_dppo.objective",
    "shared_variance_gaussian_kl": ".flow_policy.reference_kl",
    "MAX_SEQUENCE_LOG_RATIO": ".token_policy.objectives",
    "NativeTokenPolicyEngine": ".token_policy.engine",
    "NativeTokenPolicyTrainingSession": ".token_policy.session",
    "NativeTokenPolicyTrainingStack": ".token_policy.builder",
    "PackedTokenReplayBatch": ".token_policy.contracts",
    "PackedTokenTrajectory": ".token_policy.contracts",
    "SEQUENCE_MEAN_TOKEN_MEAN": ".token_policy.reduction",
    "SEQUENCE_MEAN_TOKEN_SUM_NORMALIZED": ".token_policy.reduction",
    "TOKEN_MEAN": ".token_policy.reduction",
    "TOKEN_POLICY_ENGINE_STATE_SCHEMA": ".token_policy.engine",
    "TokenCPPOStage": ".token_policy.stages",
    "TokenDPPOStage": ".token_policy.stages",
    "TokenDRPOStage": ".token_policy.stages",
    "TokenGRPOStage": ".token_policy.stages",
    "TokenGSPOStage": ".token_policy.stages",
    "TokenObjective": ".token_policy.objectives",
    "TokenPolicyIterationResult": ".token_policy.session",
    "TokenPolicyReplayAdapter": ".token_policy.contracts",
    "TokenPolicyRolloutAdapter": ".token_policy.contracts",
    "TokenPolicyStage": ".token_policy.stages",
    "TokenPolicyStageLoss": ".token_policy.stages",
    "TokenPolicyStepResult": ".token_policy.engine",
    "TokenReplayResult": ".token_policy.contracts",
    "TokenRolloutRequest": ".token_policy.contracts",
    "TokenTrajectoryRewardAdapter": ".token_policy.contracts",
    "build_native_token_policy_training_stack": ".token_policy.builder",
    "build_token_policy_stage": ".token_policy.runtime",
    "expand_sequence_values": ".token_policy.packing",
    "packed_token_offsets": ".token_policy.packing",
    "slice_packed_token_trajectory": ".token_policy.packing",
    "token_cppo_objective": ".token_policy.objectives",
    "token_dppo_objective": ".token_policy.objectives",
    "token_drpo_objective": ".token_policy.objectives",
    "token_grpo_objective": ".token_policy.objectives",
    "token_gspo_objective": ".token_policy.objectives",
}

__all__ = list(_EXPORTS)


def __getattr__(name: str) -> object:
    module_name = _EXPORTS.get(name)
    if module_name is None:
        raise AttributeError(name)
    value = getattr(import_module(module_name, __name__), name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(__all__))
